### PR TITLE
Add ssl pod dependency to be able to compile on 10.11+

### PR DESCRIPTION
**Pull request by Sega-Zero**
Couldn't create an issue, so creating a pull-request.
This dependency works for me on 10.11+, can't verify on `pod spec lint`, since it needs 0.2.0 tag on remote, but when specifying in `Podfile` it works well.

### CODE REVIEW

**Comment by vslavik** [comment]
You still left linking against system-provided libcrypto in there, which is clearly wrong...

**Comment by Sega-Zero** [comment]
I'm not sure yet about correct Podspec structure. crypto present on an older OS X. Maybe it is better to add a podspec that should be included in Podfile for projects that build on 10.1+ and add a `'OpenSSL-OSX'` dependency there. Or should we add `s.prepare_command` and build openssl without any external dependencies.

**Comment by vslavik** [comment]
There's no reason to treat compilation on 10.11 and on older systems any differently. There's also no reason other than convenience (which the Podfile eliminates) to use the ancient, long-deprecated system-provided copy of OpenSSL. On the contrary, it's significantly *better* to use an internal static library, often updated, then dynamically linked libcrypto, because the latter can be trivially bypassed, the former can not.

**Comment by vslavik** [comment]
So... any chance of getting a fixed spec?

**Comment by Sega-Zero** [comment]
Sorry, had not enough free time. Removed libcrypto dependency from the podspec, but `pod spec lint` fails for now because of [broken dependency pod](https://github.com/GerTeunis/OpenSSL-OSX-Pod/issues/6). Not sure if we should wait for issue closing or copy `s.prepare_command` command from there and patch it to download latest [OpenSSL release](https://github.com/openssl/openssl/releases/)

**Comment by vslavik** [comment]
> Not sure if we should wait for issue closing

Definitely. The point of having it as a dependency is that you don't include multiple copies of OpenSSL in the binary.

I don't see any reason for 061d5fb and 97f74fb being separate commits when they do one thing...

**Comment by Sega-Zero** [comment]
No, they're not. [`s.dependency`](https://guides.cocoapods.org/syntax/podspec.html#dependency) is a cocoapod dependency (this pod needs to include another pod in order to work properly), while [`s.library`](https://guides.cocoapods.org/syntax/podspec.html#libraries) is a project linking dependency on libcrypto (which is, basically, done in `OpenSSL-OSX` pod as well).

There is a problem with `pod spec lint`: it reports an error
>`The 'Pods' target has transitive dependencies that include static binaries 

so I'm not sure that `pod trunk register` will succeed. Cannot check this out, since I'm not the repo owner. If it'll fail, then we have 2 ways of solving:
1. Build static ssl library by ourselves 
2. Mention external ssl dependency in Readme.md

**Comment by vslavik** [comment]
No they are. It's a single *logical* change: replacing system library with a pod dependency. The first commit doesn't stand on its own because it's broken. The second only fixes it. Self-contained commits (with good, best practices following message) are good git hygiene. Please rebase into a clean history.

**Comment by Sega-Zero** [comment]
Done

**Comment by vslavik** [comment]
> There is a problem with pod spec lint: it reports an error

This is apparently a widespread issue with the new versions: https://github.com/CocoaPods/CocoaPods/issues/3194 — yet another poorly thought out design choice in CocoaPods (case in point: see how all the various OpenSSL pods grossly and disgustingly prebuild thing, because there's just no other way).

My reading of that issue is that there's simply nothing that could be done and I should push the spec with `--use-libraries`, at least until they sort it out. Right?

Embedding a copy of OpenSSL in this pod doesn't seem reasonable, it can be a dependency of multiple targets and all sorts of interesting linking *and* runtime issues would pop up then.

**Comment by Sega-Zero** [comment]
I also think that embedding ssl may lead to troubles, so there are two choices: 
1. push with `--use-libraries` or 
2. discard static OpenSSL library dependency from the podspec, mention it in Readme.md and push to trunk
Both looks satisfying enough.

**Comment by vslavik** [comment]
> 2. discard static OpenSSL library dependency from the podspec, mention it in Readme.md and push to trunk

Sorry for the delay, was hoping CocoaPods would sort the mess out. Well, that’s not going to happen :( 

I tried this solution as somewhat cleaner in the end, I think, but alas, that didn’t go over well:
```
Validating podspec
 -> EllipticLicense (0.1.1)
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [OSX] xcodebuild:  EllipticLicense/c_api/elliptic_license.c:30:10: fatal error: 'openssl/sha.h' file not found
```

Back to doing 1. then...

**Comment by vslavik** [comment]
OK, that worked. Pushed to the ofificial repo now.

Thanks!

**Comment by Sega-Zero** [comment]
👍 great!

**Pull request closed without merging**
